### ISSUE TITLE
recent get_kernel change from #897

### ISSUE THREAD

**Issue by schaefi** [SUSE/kiwi#899] opened 2018-12-10 08:24 UTC
## Problem description

Sorry guys but why got #897 merged the way it was coded ? There are several issues mostly related to code quality.

1. I wrote a good reason in the code why in case of zImage we use vmlinux.gz to read the kernel version. In the change of #897 no such reason to make it clear was given and I also don't understand why it should be needed. I'm running Leap15 and a simple ```kversion /boot/vmlinuz-4.12.14-lp150.12.22-default``` on x86_64 worked without any problem. Thus give me a good reason such that one reading the code understands why we are doing it

2. If we need another exception to the standard way it can be done much simpler
    ```if 'zImage' in kernel_file_to_check or ...``` There is no need for an extra block unless we decide
   this check depends on the architecture. All this was done in the scope of s390 but impacts all other
   archs because a vmlinuz version of the kernel is presented in other archs too but having the safe
   vmlinux.gz version around is not guaranteed. Thus I'm rather concerned than happy with this change

3. The ```os.path.exists(new_file_to_check)``` is superfluous and misleading. We use the rewritten
    target to run kversion on for a reason and call the command with ```raise_on_error=False``` if our 
    expectations are proven wrong I want to see that in the log and not got confused by an extra
    condition based on an assumption.

## Expected behaviour

Don't let us start to again mess up the kernel lookup with code paths nobody understands

I'll come up with a fix as I see it fit and then we can discuss what is wrong or needs further changing

Really wonder why #897 got merged

**Comment by schaefi** [comment] 2018-12-10 08:45
Also see:

* osc rbl Virtualization:Appliances:Images:Testing_x86 test-image-vmx images x86_64  | grep kversion

which builds Factory against x86_64 and has no problem with vmlinuz. Thus I don't want to change the working parts

**Comment by davidcassany** [comment] 2018-12-10 09:03
@schaefi I merged that last week. Sorry I should have waited before merging.

> 1. I wrote a good reason in the code why in case of zImage we use vmlinux.gz to read the kernel version...

Yes you are right. A proper explanation for this case is not included.

> 2. If we need another exception to the standard way it can be done much simpler...

In this case I though it was good not to include arch specific code, since I understand to root cause @bugfinder exposed is not necessarily tight to certain arch.

> 3. The os.path.exists(new_file_to_check) is superfluous and misleading...

The existence of a gzip version of the file looked like a good sanity check to me. I considered there is no chance to get a wrong parallel kernel file matching the criteria, it is already a very constrained case. I agree that the code could be misleading without a proper explanation, I certainly failed on not requiring that.

> Really wonder why #897 got merged

Sorry if that doesn't match our desired quality standards. It was me who decided the patch was good enough to be merged, my bad in this case.

**Closed** 2018-12-11 07:18 UTC
