### ISSUE TITLE
apt-build not working anymore

### ISSUE THREAD

**Issue by msrex** [SUSE/kiwi#370] opened 2017-06-08 19:40 UTC
Kiwi 9.7.1, Leap 42.2

I tried building an Ubuntu-image for the first time in about 2 weeks, with an unchanged configuration (sample config from kiwi-descriptions with only mirror-location changed).

Setting up the apt repos an error pops up in `apt.py`.

Attached are the output and the debug log.

Here the pertinent part:
```[ WARNING ]: 14:55:46 | locale setup skipped etc/sysconfig/language not found
[ INFO    ]: 14:55:46 | Setting up timezone: America/New_York
[ ERROR   ]: 14:55:46 | Unexpected error:
Traceback (most recent call last):
  File "/usr/bin/kiwi", line 9, in <module>
    load_entry_point('kiwi==9.7.1', 'console_scripts', 'kiwi-ng-3')()
  File "/usr/lib/python3.4/site-packages/kiwi/kiwi.py", line 54, in main
    App()
  File "/usr/lib/python3.4/site-packages/kiwi/app.py", line 35, in __init__
    task_class().process()
  File "/usr/lib/python3.4/site-packages/kiwi/tasks/system_prepare.py", line 225, in process
    setup.import_repositories_marked_as_imageinclude()
  File "/usr/lib/python3.4/site-packages/kiwi/system/setup.py", line 125, in import_repositories_marked_as_imageinclude
    repo.use_default_location()
  File "/usr/lib/python3.4/site-packages/kiwi/repository/apt.py", line 113, in use_default_location
    self._write_runtime_config(system_default=True)
  File "/usr/lib/python3.4/site-packages/kiwi/repository/apt.py", line 244, in _write_runtime_config
    apt_conf_data = template.substitute()
  File "/usr/lib64/python3.4/string.py", line 125, in substitute
    return self.pattern.sub(convert, self.template)
  File "/usr/lib64/python3.4/string.py", line 115, in convert
    val = mapping[named]
KeyError: 'unauthenticated'
[ INFO    ]: 14:55:46 | Cleaning up SystemPrepare instance
[ WARNING ]: 14:55:46 | Path /root/build/full-image/ubuntu-datto/vmroot/ubuntu-bios-dracut/image-root/dev not a mountpoint```

[prepare-log.txt](https://github.com/SUSE/kiwi/files/1062197/prepare-log.txt)
[stdout.txt](https://github.com/SUSE/kiwi/files/1062196/stdout.txt)

**Comment by schaefi** [comment] 2017-06-09 08:29
The problem is in repository/apt.py::_write_runtime_config() a template.substitute must always provide all parameters of the template. If system_default is set to true template.substitute() is called without the hash keys used in the template and you run in the key error

**Comment by schaefi** [comment] 2017-06-09 08:32
I have missed that in the review, sorry and the unit test says:

```
template.substitute.assert_called_once_with()
```

which is a wrong test

**Comment by schaefi** [comment] 2017-06-09 08:33
This should be fixed with prio 1

**Comment by davidcassany** [comment] 2017-06-09 08:54
Sure, I am on it, I had a meeting until now. Will be handled today morning.

**Closed** 2017-06-09 11:57 UTC
Labels: Bug, P1
