### ISSUE TITLE
First grub config does not include linuxefi/initrdefi

### ISSUE THREAD

**Issue by agraf** [SUSE/kiwi#628] opened 2018-02-16 10:51 UTC
## Problem description
The first generated grub config and the grub config after booting, generated via update-bootloader --refresh should be as similar as possible.

However, at least on aarch64, with firmware=efi the first generated grub.cfg only contains "linux" and "initrd" commands, while the one generated from update-bootloader --refresh contains "linuxefi" and "initrdefi" commands.

While this is broken for aarch64 (we should always emit linux/initrd commands), it means that most likely on x86 we don't generate linuxefi/initrdefi commands in the first grub.cfg. That again means we do not get EFI runtime services available on the first boot which means no access to EFI boot variables, EFI capsule loaders, etc.

## Expected behaviour
On x86 with firmware=efi, the first grub.cfg should contain linuxefi/initrdefi commands.

## Steps to reproduce the behaviour
Generate an image with firmware=efi, check /boot/grub2/grub.cfg if linuxefi/initrdefi commands are emitted.

## OS and Software information
+ KIWI version: 9.12.6
+ Operating system: Tumbleweed

**Comment by schaefi** [comment] 2018-02-20 09:18
Thanks David for looking into this one

**Comment by davidcassany** [comment] 2018-02-20 16:02
To dig about this _bug_ I have been building oem images with this type:

`<type image="oem" filesystem="btrfs" bootloader="grub2" firmware="efi" boot="oemboot/suse-tumbleweed">`

And what I am experimenting is that after the first boot the grub2 configuration it does not include the linuxefi and initrdefi but it does in the first one. This is caused by booting in a non efi qemu environment;  thus so far I can't see the bug exposed in this issue. @agraf are you using a different type configuration? also the aarch64 issue I assume is what you fixed in https://github.com/SUSE/kiwi/commit/9ee21e61636e407f4fb2f0093e1ca4dc42da1fdc

@agraf could it be that first boot grub.cfg includes linuxefi command depending on the running platform? As far as I have seen up to now the first boot should get something like that in the grub2.cfg

```bash
if [ "$${grub_cpu}" = "x86_64" -o "$${grub_cpu}" = "i386" ];then    
    if [ "$${grub_platform}" = "efi" ]; then                        
        set linux=linuxefi                                          
        set initrd=initrdefi                                        
    fi                                                              
fi
```
so I assume that in aarch64 you do not see a linuxefi command because of the `grub_cpu` variables, but you did in the second boot because of a wrong `/etc/default/grub`, which now you fixed in https://github.com/SUSE/kiwi/commit/9ee21e61636e407f4fb2f0093e1ca4dc42da1fdc.

I believe there is no bug here, so I am closing it. Feel free to reopen if you think there is still something wrong.

**Closed by davidcassany** 2018-02-20 16:02 UTC
Labels: Bug

**Comment by agraf** [comment] 2018-02-20 22:28
The analysis sounds sound to me. Thanks for verifying!
