### ISSUE TITLE
CentOS ISO fails on Switch Root target

### ISSUE THREAD

**Issue by pda14** [SUSE/kiwi#741] opened 2018-05-24 13:34 UTC
## Problem description
CentOS live ISO fails on initramfs Switch Root target while boot. There's generated sysroot.mount unit which should be called from somewhere but it doesn't. 
## Steps to reproduce the behaviour
Run "kiwi-ng --color-output --type=iso system build --description ./ --target-dir /tmp/builds/"
Description was taken from https://github.com/SUSE/kiwi-descriptions/tree/master/centos/x86_64/centos-07.0-JeOS
Then feed ISO to Virtualbox
## OS and Software information
+ KIWI version: 9.15.2
+ Operating system: CentOS 7.5

**Comment by davidcassany** [comment] 2018-05-25 07:45
Verified, I can also easily reproduce it by building the mentioned image.

**Comment by davidcassany** [comment] 2018-05-25 07:54
@pda14, for the time being, while we don't find the root cause of the issue I suggest you to change the `flags="overlay"` type attribute to `flags="dmsquash"`. With this change the live dracut module used is the one provided by dracut itself, instead the kiwi provided one. With this change you loose some features like the hybrid mode and overlay persistency if deployed on a read/write disk.

**Comment by pda14** [comment] 2018-05-25 08:20
@davidcassany Thanks.
After some debugging i found that there's no generated requirements for initrd-root-fs.target such as /run/systemd/generator/initrd-root-fs.target.requires/sysroot.mount in initrd filesystem.  Maybe its because of /usr/lib/systemd/system-generators/dracut-rootfs-generator missing some crucial functions which i was found in KIWI-generated openSUSE live ISO.

**Comment by davidcassany** [comment] 2018-05-25 09:18
@pda14 thanks for sharing your thoughts and findings. I was pointing to somewhere else, I had the feeling that switch-root expects the root to be mounted in `/sysroot`, but instead it is mounted in `/run/rootfsbase`, I just tested to break before switch-root, remount to `/sysroot` and continue. It boots with a bunch of warnings (I guess caused by my brute force approach), but it boots. Probably there is something wrong with our overlay dracut module, that centos expects it in different way of how it is expected by openSUSE. I'm checking it.

**Comment by pda14** [comment] 2018-05-25 12:22
Workaround to avoid this bug:
Copy original `kiwi-generator.sh`  to `root/usr/lib/dracut/modules.d/90kiwi-live/kiwi-generator.sh`;
add to the end of script:
`mkdir -p /run/systemd/generator.early/initrd-root-fs.target.requires`
`ln -s /run/systemd/generator.early/sysroot.mount /run/systemd/generator.early/initrd-root-fs.target.requires/sysroot.mount`
Then build ISO.  Yep, there's still some warnings but they are not related.

**Comment by davidcassany** [comment] 2018-05-25 13:15
Yes, currently I am investigating how it is that the `/run/systemd/generator.early/initrd-root-fs.target.requires/sysroot.mount` is not generated automatically by systemd. Trying to figure out the proper why of setting dependecies for this systemd v219.

**Comment by davidcassany** [comment] 2018-05-25 16:38
@pda14 finally found the cause of this. The systemd version used in centos (v219) does not automatically generate sysroot mount unit if the `root=` argument from kernel command line is not an absolute path. 

The `fstab-generator` is expected to create a `sysroot.mount` with a `initrd-root-fs.target` dependency, this is how the `initrd-root-fs.target` dependency ends up in our custom `sysroot.mount`, as you noted it is not created by our generator script. Any systemd package including this commit https://github.com/systemd/systemd/commit/093c2cfe3b should work, this is not the case for v219.

Now I am trying to figure out the right way of handling this dependency, I'd like to find a _correct_ approach that works for all versions. Probably your _workaround_ is the right way of doing it, need to check or find some systemd guru.

Thanks

**Comment by schaefi** [comment] 2018-05-28 06:07
@davidcassany looks like you already did some investigations here. I'll assign this one to you if ok

**Comment by davidcassany** [comment] 2018-05-28 06:27
@schaefi, sure I am working on that one.

**Closed** 2018-05-28 14:26 UTC
Labels: Bug
