### ISSUE TITLE
suseStripKernel is not being obeyed for non iso

### ISSUE THREAD

**Issue by cybernard** [SUSE/kiwi#689] opened 2018-04-06 12:41 UTC
## Problem description
I was clearly not clear enough the last question.
I don't want to alter the initrd fs.  I did a lsinitrd and nothing in there I want to change.

sudo kiwi-ng  --logfile="kiwi-ova.log" --profile=iso system build --description /kiwi/kiwi-descriptions/suse/x86_64/suse-tumbleweed-firewall     --target-dir /tmp/myimag2

Boot the ISO into your favorite VMWare,virtual box or etc
find /lib/modules/\<version\>\/kernel --iname "*.ko"|wc -l
result 360 modules  YAY

sudo kiwi-ng  --logfile="kiwi-ova.log" --profile=ovf system build --description /kiwi/kiwi-descriptions/suse/x86_64/suse-tumbleweed-firewall     --target-dir /tmp/myimag2

Deploy to my ESXi server and boot:
find /lib/modules/\<version\>\/kernel --iname "*.ko"|wc -l
result 4002 modules  NO

## Expected behaviour

find /lib/modules/\<version\>\/kernel --iname "*.ko"|wc -l
result 360 modules 

## Steps to reproduce the behaviour
1. Go into config.sh 
2. add suseStripKernel
3. edit config.xml
4. add \<drivers\>  (list of drivers)  \</drivers\>
(list of drivers) contains a carefully select group of 360 (or so) modules.

## OS and Software information
+ KIWI version: 9.14.1
+ Operating system: opensuse tumbleweed
+ OBS version:  not using it right now

**Comment by davidcassany** [comment] 2018-04-06 13:01
See my comments in https://github.com/SUSE/kiwi/issues/687#issuecomment-379244349, I believe this is a bug, but the intended behavior is the other way round, `suseStripKernel` should be also skipped in this iso context.

With the current dracut system I believe the documentation regarding this functions is confusing. Also, probably a review of these functions to state which of them make sense or are useful beyond the custom boot image scenario would be a good exercise to better state what is actually supported and expected of them.

**Comment by cybernard** [comment] 2018-04-06 13:09
Why should my image be forced to have 3000+ modules I will **NEVER** load.
Even the kernel developers saw the usefulness in this option as "make localmodconfig" when building the kernel from source is **officialy** supported.

**Comment by davidcassany** [comment] 2018-04-06 13:29
Sorry if my comment seamed harsh I never meant to say you are forced to include all the modules into the image.

That suseStripKernel actually gets executed in `iso` images I consider it a bug, since this was meant not to happen. In fact, it happens because the initrd_system default value for for iso images is incorrectly set, and, as a consequence, with the iso image you do not see the skip message and the method gets executed.

This method was written to slim down the inirtd when this is provided by KIWI, instead of dracut. You are using it to remove modules from the system and I understand your you case, but this code was not designed to do that. I am just putting in doubt this is something that is part of KIWI duties, that's why I suggest reviewing this functions and analyze if we support them or not beyond the scope in which they were initially thought.

You will always have the chance to run some specific code into config.sh and hack the root tree.

**Comment by cybernard** [comment] 2018-04-06 15:01
1.  Under what conditions is suseStripKernel supposed to execute?
The initrd isn't big enough to worry about really, and there is a separate **suseStripInitrd** function!
It seems to me suseStripKernel is functioning as it was meant to especially given the existence of **suseStripInitrd**.

The initrd is approx 27MB(approx) and the kernel modules are 259M(approx) is obvious here to see which one **needs** striping.

You can do whatever you want with **suseStripInitrd**, but give the exists of the former command **suseStripKernel** is functioning as intended.  I don't know the internal working of the system, but the documentation and everything I read seems to indicate it is supposed to work that way.

Is there a way I can modify the program to apply this feature universally?

I know you say I can write my own specific code in config.sh, but ....

    1.  I don't know what to put in there
    2. It seems like redundant code duplication given the code already exists.
    3. Doubly redundant since now I have to add this to **every** config.sh I write.
    4.  It **seems** the changing the code to allow this would be trivial compared to what I need to do.

**Comment by cybernard** [comment] 2018-04-06 15:38
I have done further testing against suseStripInitrd
You suggest the function is meant to only function against the initrd

Well there again it only works for ISO!

The initrd is 13,405KB for an ISO build
The initrd is 25,332KB for an ova build

Clearly it doesn't even strip the initrd properly unless your building an ISO

**Comment by davidcassany** [comment] 2018-04-09 08:59
Removing bug flag, since #690 is merged.

> Also the ISO is unbootable with the suseStripInitrd as too much is removed.

Yes, `suseStripInitrd` should not be used in this case. With #690 the sanity check will work as expected and `suseStripInitrd` will not delete anything. The same applies for `suseStripKernel.`

**Closed by davidcassany** 2018-04-09 08:59 UTC
