### ISSUE TITLE
No messages are shown when using plymouth

### ISSUE THREAD

**Issue by Jellyfrog** [SUSE/kiwi#503] opened 2017-09-19 08:58 UTC
## Problem description
When using plymouth bootsplash, no console/debug/text is shown when pressing escape/home to show messages

## Steps to reproduce the behaviour
1. Create kiwi image with
```
<type image="oem" kernelcmdline="splash quiet net.ifnames=1" filesystem="btrfs" fsmountoptions="acl" boot="netboot/suse-SLES12" installiso="false" bootloader="grub2" boottimeout="5" bootprofile="default" installpxe="true">
...
<bootloader-theme>SLE</bootloader-theme>
...
<package name="plymouth-branding-SLE" bootinclude="true" />
```
2. Add a kiwi-hook, for example "postnetwork.sh" with:
`dialog --nocancel --title "MR KIWI" --pause "HELLO THERE MR KIWI" 10 70 60`
2. Extract `pxeboot.initrd.xz` and `pxeboot.kernel` from  `foobar.install.tar.xz`
3. PXE those files, we use iPXE like so:
```
kernel pxeboot.kernel splash quiet net.ifnames=1 
initrd pxeboot.initrd.xz
```
4. Wait for bootsplash to show up
5. Press escape
6. Blank screen instead of  showing the  dialog

![kiwi1](https://user-images.githubusercontent.com/759887/30588525-4e35ecfe-9d37-11e7-99b0-84cca3408ae0.png)
When pressing escape:
![kiwi2](https://user-images.githubusercontent.com/759887/30588530-506ab45a-9d37-11e7-9afe-37f2de99d6f5.png)

**Comment by davidcassany** [comment] 2017-09-20 13:16
@Jellyfrog I could not reproduce the issue. In my tests of pxe and oem images and the plymouth splash showed as expected and it also disappeared if ESC was pressed.

Also, there is something inconsistent with your <type> section, note that you are requesting an oem image type but using the netboot image. The boot attribute should be something like `boot="oemboot/suse-SLES12"`. Note that the postnetwork.sh is hook only present for the netboot initrd scripts which should be used with pxe images (`image="pxe"`).

**Comment by Jellyfrog** [comment] 2017-09-20 14:37
It only shows a blank screen when pressing escape (see screenshot).
Switched to `<type image="pxe" kernelcmdline="splash quiet net.ifnames=1" boot="netboot/suse-SLES12" filesystem="btrfs"/>`
Same result.

**Comment by davidcassany** [comment] 2017-09-21 09:34
I did some further tests using `<type image="pxe" kernelcmdline="splash quiet net.ifnames=1" boot="netboot/suse-SLES12" filesystem="btrfs"/>` to build a pxe image of SLE12-SP2. Also including the postnetwork.sh hook and also `<package name="plymouth-branding-SLE" bootinclude="true"/>` with `<bootsplash-theme>SLE</bootsplash-theme>` on preferences and I could see the splash and log messages as expected after pressing ESC.

I can't reproduce your problem, I am sorry but I don't see what else can I do.

**Comment by davidcassany** [comment] 2017-09-22 09:31
In my tests I forgot to update the `/srv/tftpboot/pxelinux.cfg/default` with the above selected kernel parameters (including `quiet`). @Jellyfrog realized the difference between my deployment and his deployment was the absence of the quiet parameter, removing it solves the issue. Closing the ticket.

**Closed by davidcassany** 2017-09-22 09:31 UTC
